#!/bin/bash
source docker/function

echo -e "${GRN}Starting pull${FIN} ..."
docker_cross > /dev/null 2>&1
docker-compose pull && docker-compose up -d
#docker_cbuild > /dev/null 2>&1
sudo docker-compose --compatibility up -d --build
docker exec -it arm-img-builder bash
