#!/bin/bash
source userdata
source docker/function

start_ubuntu_native(){
echo -e "${GRN}Starting pull${FIN} ..."
ubuntu_native > /dev/null 2>&1
docker-compose pull && docker-compose up -d
docker_nbuild > /dev/null 2>&1
sudo docker-compose --compatibility up -d --build
docker exec -it arm-img-builder bash
}

start_debian_native(){
echo -e "${GRN}Starting pull${FIN} ..."
debian_native > /dev/null 2>&1
docker-compose pull && docker-compose up -d
docker_nbuild > /dev/null 2>&1
sudo docker-compose --compatibility up -d --build
docker exec -it arm-img-builder bash
}

if `grep -Fx "ubuntu=1" "userdata" >/dev/null;`
	then start_ubuntu_native;
fi
if `grep -Fx "debian=1" "userdata" >/dev/null;`
	then start_debian_native;
fi
