#!/bin/bash
source docker/function

echo -e "${GRN}Running git pull${FIN} ..."
cd /build/rpi-img-builder && make bmakefile > /dev/null 2>&1
git pull
cd ../debian-image-builder && make bmakefile > /dev/null 2>&1
git pull
cd /build/rpi-img-builder && make dmakefile > /dev/null 2>&1
cd ../debian-image-builder && make dmakefile > /dev/null 2>&1
cd ..
echo -e "${GRN}Done${FIN}."
