#!/bin/bash
source docker/function

remove(){
rm -f Makefile
rm -f docker/*
}

update(){
wget -cq --show-progress https://raw.githubusercontent.com/pyavitz/arm-img-builder/main/Makefile
mkdir -p docker
wget -cq --show-progress -P docker https://raw.githubusercontent.com/pyavitz/arm-img-builder/main/docker/setup
wget -cq --show-progress -P docker https://raw.githubusercontent.com/pyavitz/arm-img-builder/main/docker/pull
wget -cq --show-progress -P docker https://raw.githubusercontent.com/pyavitz/arm-img-builder/main/docker/update
wget -cq --show-progress -P docker https://raw.githubusercontent.com/pyavitz/arm-img-builder/main/docker/function
}

echo -e "${GRN}Updating files${FIN} ..."
remove
update
echo -e "${GRN}Done${FIN}."
